name: Jest

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'appinfo/info.xml'
      - '*.js'
      - '*.json'
  push:
    branches:
      - main
      - master
      - stable*

concurrency:
  group: jest-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    name: node
    steps:
      - uses: actions/checkout@v3

      - name: Read package.json node and npm engines version
        uses: skjnldsv/read-package-engines-version-actions@v1.2
        id: versions
        with:
          fallbackNode: '^16'
          fallbackNpm: '^7'

      - name: Set up node ${{ steps.versions.outputs.nodeVersion }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.versions.outputs.nodeVersion }}

      - name: Set up npm ${{ steps.versions.outputs.npmVersion }}
        run: npm i -g npm@"${{ steps.versions.outputs.npmVersion }}"

      - name: Install dependencies
        run: npm ci

      - name: Run jest
        run: npm run test --colors
